### ISSUE TITLE
New implementation of boundary.c

### ISSUE THREAD

**Issue by IgorTo** [MakisH/CFDLab#12]
Since you (Martin) proposed a discussion in your commit message, I just have a few thoughts about the code..
- Is it really negligible if we get rid of the if-statements? This can be easily done in a way I treated the boundary initialization (initLB.c)
- I think the link (https://github.com/POWER-Morzh/CFDLab02/blob/master/boundary.c) that you mention in the code still uses if-statements without a reason?

About the correctness: it seems correct to me.

**Comment by martosss** [comment]
Yes ,that will work for the first if statement (with the FLUID check ) but the second if remains a mistery (:shit:)

**Comment by martosss** [comment]
So the second "if" is related to the comment from Makis' issue - https://github.com/MakisH/CFDLab/issues/5

**Comment by MakisH** [comment]
I think we can safely put the boundary discussion asside now!
