### ISSUE TITLE
Visualization after optimiziation

### ISSUE THREAD

**Issue by IgorTo** [MakisH/CFDLab#13]
visualLB.c does not produce a good .vtk file anymore. Paraview returns an error.
-   // " smart indexing ... 10% faster for 20 points(3sec), 3% for 100(10sec)
-   for (z = 0; z <= 1; z+=dz){
-       for (y = 0; y <= 1; y+=dy){
-           for (x = 0; x <= 1; x+=dx){
-               fprintf(fp, "%f %f %f\n", x, y, z);
          }
      }
  }
  }

By this approach, we loose 1 point per set, so we have (xlength-1)^3 points. The problem is with boundaries of for loop and incrementing the step by itself, since you can encounter a situation where the last calculated point is 1.000000001, although it should be 1.0. So I think this problem is a manner of precision.

I was thinking about how to solve this:
- We can do a really small eps area and use it like for(x=0; x<=1+eps; x+=dx). But, is that safe for all situations?
- We can stick with the old unoptimized implementation.

**Comment by martosss** [comment]
Added eps = deltaD/2. this should be working.
