### ISSUE TITLE
Handle different sizes in x,y,z

### ISSUE THREAD

**Issue by MakisH** [MakisH/CFDLab#14]
Substitute xlength by an array xlength[3]. Make the corresponding changes in reading and wherever needed. Do not forget to update the function signatures from "int xlength" to "int *xlength".

**Comment by martosss** [comment]
Many, if not all, files are going to be changed here...

**Comment by martosss** [comment]
And after a little bit of moving commits around, this is fixed, note that the collision file should still be changed to treat arbitrary geometries.
