### ISSUE TITLE
Handle different types of boundaries

### ISSUE THREAD

**Issue by MakisH** [MakisH/CFDLab#15]
From the worksheet:
Add the handling of the boundary cells of type FREE_SLIP, INFLOW, OUTFLOW and PRESSURE_IN in the function void treatBoundary(). The input parameter wallVelocity is to be substituted by an array of parameters, which are required to set the inflow velocity and the artificial input pressure for a pressure inlet. Note that readParameters() has to be updated accordingly to be able to steer the simulation without the need for recompilation.

**Comment by martosss** [comment]
I'm looking at the Free-Slip - at the corner we should simply stream the cell velocity, but what are we doing with the diagonal probability from the "corner" boundary cell ?
