### ISSUE TITLE
Adjust initialiseFields()

### ISSUE THREAD

**Issue by MakisH** [MakisH/CFDLab#16]
From the worksheet:
Adjust initialiseFields(), so that the *flagField is set with the appropriate flags according to the desired geometry. The signature of initialiseFields() is extended by *char problem, which contains the name of a chosen scenario. In initialiseFields() the *flagField is then set according to a given scenario. Note that this scenario should be created independent from the used domain size *xlength to allow a change of resolution of the simulation. Furthermore read_pgm can be used to initialize the *flagField to create scenarios more easily.

**Comment by martosss** [comment]
I think in this function we must also check for forbidden cells, probably after initializing dimensions and the flag field.

**Comment by martosss** [comment]
- pgm copied and changed to fit our needs;
- partial scalability implemented(still takes 2D input)
  1 task closed, 2 new tasks opened. The joy of code. :)
