### ISSUE TITLE
[FIXED] Worksheet 2: Density is >1 for some points

### ISSUE THREAD

**Issue by MakisH** [MakisH/CFDLab#2]
See the output .vtk files.

**Comment by IgorTo** [comment]
Question:
computeCellValues.c, computeDensity(): we iterate the loop on interval [1, Q_NUMBER). Is there any particular reason not to do it on [0, Q_NUMBER)?

**Comment by martosss** [comment]
density is initialized with *currentCell, which is currentCell[0], that's why I don't touch it anymore.

**Comment by IgorTo** [comment]
Martin answered: because the variable in which we store the sum is initialized with the first value.

**Comment by IgorTo** [comment]
streaming.c: bug in the most inner for loop fixed. Otherwise, everything seems OK.

**Comment by IgorTo** [comment]
boundary.c: it appears, the problem was in bad indexing of inv_i variable on line 115.

Now, we get good densities. Didn't check them for all of the time steps, but it seems they don't exceed 1.05.
