### ISSUE TITLE
InitialiseField() scalability

### ISSUE THREAD

**Issue by martosss** [MakisH/CFDLab#23]
regarding the tilted plate scenario...
To what extent should the initialiseField() be scalable - if we want to support 3D input from a file(currently 2D is hardcoded, even in the pgk_read() function ) it's gonna be a bit trickier and I plan to leave this out of scope for now and implement just the 2D input from a file(like the pgk_read() supports)

**Comment by MakisH** [comment]
I think that reading 3D input is too much for now. If I remember correctly,
Sebastian said that we will just extend the the 2D to the 3rd dimension.

**Comment by martosss** [comment]
OK, I was thinking the same thing, so that's decided for now.
