### ISSUE TITLE
Initialisation: read boundary conditions from configuration

### ISSUE THREAD

**Issue by MakisH** [MakisH/CFDLab#26]
I think we should read the types of boundary conditions from the file instead of hard-coding them to the initialisation function. We are actually only allowed to hard-code special boundary conditions, like inlet for specific scenarios.

We also should be able to read an arbitrary configuration and geometry file (if it doesn't require any special, hard-coded, boundary conditions)

Though, we could leave it for a bit later if it is so difficult. First we need something working. :-)

**Comment by martosss** [comment]
I actually implemented the reading of the 2D file in the initialize fields already :+1: OK then, for the boundary initialization, I will pass these extra parameters to the initialiseFields() and do that, too, it will actually simplify things, since I'll do the same thing for every scenario.

**Comment by martosss** [comment]
done.
