### ISSUE TITLE
Add moving-wall velocity in configuration files (or drop the feature)

### ISSUE THREAD

**Issue by MakisH** [MakisH/CFDLab#27]
When I extended the configuration file from the Worksheet 2, I left the "moving wall" option as a boundary condition but I didn't keep a "moving wall velocity" parameter.

Although we don't have this in one of the given scenarios, we should decide if we want to implement also this or delete this option. If implemented, we should also read another parameter during the initialisation.

I think we can do it, so martoss keep this change in mind! :-)

**Comment by martosss** [comment]
done. ( but do we really need it ? )
