### ISSUE TITLE
Performance: option to specify the locations of the obstacles

### ISSUE THREAD

**Issue by MakisH** [MakisH/CFDLab#28]
I have an idea:
I think that this time we should implement the most naive implementation for the boundaries and obstacles, that is, to check every cell for its type and act accordingly if it is a boundary.

Though, I just thought of a performance extension: we should provide the program with a hint of where boundaries really exist. That is, for example, "there is a boundary somewhere in x=[x1,x2]". This can be done either automatically (by examining the file once) or by the user.

Then, we can implement something like the "for(i=xmin, i<xmax, i++)" implementation of Worksheet 2 for each obstacle, combined with an array of xmins and xmaxs and another for loop that iterates between each region.

It is not necessary and it is a bit complicated, so we should implement it last or even at a next worksheet.

**Comment by martosss** [comment]
I was also thinking about this, but if you have a lot of alternating fluid and boundary cells(think of "bar code" pattern :-) ), you will code many elements and hence increase the memory usage too much. I agree with you for the naive implementation this time .. let's keep it simple, at least until we implement the basic functionality .. after that we can play around with stuff.

**Comment by martosss** [comment]
not gonna happen
