### ISSUE TITLE
Check for forbidden boundary cells

### ISSUE THREAD

**Issue by MakisH** [MakisH/CFDLab#32]
Implement this in InitLB.c. As we assume extension is the 3rd dimension, we can just check if the cell has more than two fluid boundaries, as in the 2D case.

This can be implemented later, our scenarios do not pose this danger.

**Comment by martosss** [comment]
this is not enough to test for forbidden combinations... in general we need also to check for 
FFF
BBB - middle cell is invalid, although it has 2 neighbours
FFF

or

BBFF
BBFF - again confliict in the middle - it's not a proper corner
FFBB
FFBB
