### ISSUE TITLE
Check i j k initialization once again...

### ISSUE THREAD

**Issue by martosss** [MakisH/CFDLab#41]
```
if (rank % (iProc*kProc) >= iProc*(kProc - 1)) {
```

this is the condition for moving wall on z ... I think it doesn't work in the case i j k = 2 2 4 ...

**Comment by IgorTo** [comment]
![2015-06-22 00 28 57](https://cloud.githubusercontent.com/assets/9537602/8273628/7e720f76-1876-11e5-9846-109a3fb4193c.jpg)

It works..

**Comment by martosss** [comment]
This is changed ... now processors are 
...
10 11
8 9

6 7
4 5

2 3
0 1

i.e. x == i, y==j, z == k and both cells and processors are increasing in this order ... ijk and xyz.
