### ISSUE TITLE
Set exact building dimensions

### ISSUE THREAD

**Issue by martosss** [MakisH/CFDLab#43]
We have 
1. Big rectangular main hall
2. 10 x rectangular wings
We need to calculate the Area of 1. as Kaveh did and set the proportions, i.e. fix the geometry with exact values.

**Comment by MakisH** [comment]
The dimensions of the "actual" building are given in the Geometry/geometry_sizes.ods file. I can also give you the specifications for a geometry with only rectangles. The main task is then to define the problem in LBM-like dimensionless parameters.
