### ISSUE TITLE
Integrate pgm-file input from WS3 for the flagField input

### ISSUE THREAD

**Issue by martosss** [MakisH/CFDLab#48]

**Comment by MakisH** [comment]
I had started creating a script to create the geometry for different resolutions and so on but it looks like we are not going to use such a complex geometry, so there is no need for such a complicated script. Do you think there is any point in continuing developing this?

I could manually create some "vtk" files like in WS3, mainly for the main hall.

Oh, and we want it in 3D, right?

**Comment by martosss** [comment]
For the nature of the pgm file, let's start in 2D, as Kaveh proposed... we will then scale if everything works as expected.

this is a short plan for this task, as I see it:
- char scenName[20];
- Read_parameters => READ_STRING(szFileName, problem);
- take actions if the Problem is different!
- Bcast Problem
- initializeFields differently w.r.t different Problem values(same as in W3, but in a parallel environment this time)
